apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv
  labels:
    app: redis-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: ~/workbench/db/redis-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-log-pv
  labels:
    app: redis-log
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: ~/workbench/logs/redis.log
