apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: fpga
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: redis-data
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-log-pvc
  namespace: fpga
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: redis-log
  resources:
    requests:
      storage: 1Gi
