apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vboard-pvc
  namespace: fpga
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: vboard-log
