apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdu-vboard
  namespace: fpga
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: hdu-vboard
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
