apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fpga

resources:
  - ../../namespaces/fpga.yaml
  - ../../storage/pv/mysql-pv.yaml
  - ../../storage/pv/redis-pv.yaml
  - ../../storage/pvc/mysql-pvc.yaml
  - ../../storage/pvc/redis-pvc.yaml
  - ../../base/mysql.yaml
  - ../../base/redis.yaml
  - ../../base/nacos.yaml
  - ../../base/seata.yaml
  - ../../base/zookeeper.yaml
  - ../../base/rocketmq-namesrv.yaml
  - ../../base/rocketmq-broker.yaml
  - ../../base/hdu-vboard.yaml
  - ../../config/broker-config.yaml
  - ../../config/seata-config.yaml
  - ../../config/redis-config.yaml

patchesStrategicMerge:
  - mysql-config.yaml
  - hdu-vboard-config.yaml
