services:
  hdu-vboard:
    image: hdu-vboard:test          # 使用你刚构建的镜像
    container_name: hdu-vboard-test
    #    build:
    #      context: ./                   # 如果你希望 compose 自动 build
    #      dockerfile: Dockerfile
    working_dir: /workspace
    ports:
      - "9999:9999"                 # 暴露 Spring Boot 端口
    volumes:
      # 可选：开发阶段挂载本地 jar，覆盖镜像内的 jar
      - ~/Desktop/workbench/hdu_willow/hdu-vboard/target/hdu-vboard-0.0.1.jar:/workspace/target/hdu-vboard-0.0.1.jar
      # 如果需要挂载日志或其他文件也可以加
      - ~/Desktop/workbench/hdu_willow/hdu-vboard/logs:/workspace/logs
    environment:
      SPRING_PROFILES_ACTIVE: prod   # 默认 profile，可被 jar 参数覆盖
    command: [ "java", "-jar", "/workspace/target/hdu-vboard-0.0.1.jar", "--spring.profiles.active=prod" ]
#    depends_on:
#      - mysql
#      - redis
#      - nacos
    networks:
      - fpga-net

networks:
  fpga-net:
    external: true
