server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MySQL142536
    url: jdbc:mysql://localhost:3306/hdu-interrupt?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
  application:
    name: hdu-auth
  redis:
    host: localhost
    port: 6379
    database: 2
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: cea83c1b-7a99-4bb1-8596-895a4faab520
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
    group: dubbo
    register-mode: interface
    parameters:
      namespace: c29600b0-2e5d-450b-bab0-e56d78292d51
  metadata-report:
    address: nacos://localhost:8848
seata:
  service:
    vgroup-mapping:
      hdu-account-seata-service-group: default
      hdu-interrupt-seata-service-group: default
      hdu-fpga-seata-service-group: default
      hdu-record-seata-service-group: default
      hdu-auth-seata-service-group: default
    grouplist:
      default: localhost:8091
cors:
  allowed-origins:
    "TODO"

sa-token:
  # Token名称
  token-name: satoken
  # Token有效期
  timeout: 2592000
  # Token风格
  token-style: uuid

  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间
    timeout: 10s

logging:
  level:
    com.hdu.hdufpga.service: debug