registry {
  type = "nacos"
  nacos {
    application = "seata-server"
    serverAddr = "nacos-composed:8848"
    namespace = ""
    cluster = "default"
  }
}

config {
  type = "nacos"
  nacos {
    serverAddr = "nacos-composed:8848"
    namespace = ""
    group = "SEATA_GROUP"
    dataId = "seataServer.properties"
  }
}